# Generated by Django 3.0.8 on 2020-07-17 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20200716_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweets',
            options={'verbose_name': 'Tweet', 'verbose_name_plural': 'Tweets'},
        ),
    ]
