# Generated by Django 3.0.8 on 2020-07-20 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tweets', '0003_auto_20200717_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='user',
        ),
        migrations.AddField(
            model_name='tweets',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Profile'),
        ),
    ]
