# Generated by Django 3.0.8 on 2020-07-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20200720_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='profileUser',
            new_name='tweetUser',
        ),
    ]
