# Generated by Django 3.0.8 on 2020-07-30 16:17

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_auto_20200720_1634'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tweets',
            managers=[
                ('retweet_obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='tweets',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tweets.Tweets'),
        ),
    ]
