# Generated by Django 3.0.8 on 2020-08-10 12:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0007_auto_20200730_2202'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tweets',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='tweets',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
